const pages = {
  WareHouseList: () => import('./views/basic/wareHouse/index.vue'),
  SupplyChainsByItem: () => import('./views/basic/supplyChains/byItem/index.vue'),
  SupplyChainsBySupply: () => import('./views/basic/supplyChains/bySupply/index.vue'),
  RawInOrderList: () => import('./views/order/in/rawInOrder/index.vue'),
  RawInDetailList: () => import('./views/order/in/rawInDetail/index.vue'),
  FinishedInOrderList: () => import('./views/order/in/finishedInOrder/index.vue'),
  FinishedInDetailList: () => import('./views/order/in/finishedInDetail/index.vue'),
  SaleOutOrderList: () => import('./views/order/out/saleOutOrder/index.vue'),
  SaleOutDetailList: () => import('./views/order/out/saleOutDetail/index.vue'),
  RawOutOrderList: () => import('./views/order/out/rawOutOrder/index.vue'),
  RawOutDetailList: () => import('./views/order/out/rawOutDetail/index.vue'),
  AdjustInOrderList: () => import('./views/order/in/adjustInOrder/index.vue'),
  AdjustInDetailList: () => import('./views/order/in/adjustInDetail/index.vue'),
  AdjustOutOrderList: () => import('./views/order/out/adjustOutOrder/index.vue'),
  AdjustOutDetailList: () => import('./views/order/out/adjustOutDetail/index.vue'),
  InvFlowList: () => import('./views/stock/invflow/index.vue'),
  LotList: () => import('./views/stock/lot/index.vue'),
  InvFlowSumList: () => import('./views/stock/invFlowSum/index.vue'),
  InitstockList: () => import('./views/notice/initstock/index.vue'),
  TransferOrderList: () => import('./views/order/transfer/index.vue'),
  TransferInDetailList: () => import('./views/order/in/transferInDetail/index.vue'),
  TransferInNoticeList: () => import('./views/notice/transferIn/index.vue'),
  TransferOutNoticeList: () => import('./views/notice/transferOut/index.vue'),
  TransferOutOrderList: () => import('./views/order/out/transferOutOrder/index.vue'),
  TransferOutDetailList: () => import('./views/order/out/transferOutDetail/index.vue'),
  TransferInOrderList: () => import('./views/order/in/transferInOrder/index.vue'),
  InventoryPlanList: () => import('./views/order/inventory/plan/index.vue'),
  InventoryTaskList: () => import('./views/order/inventory/task/index.vue'),
};

export default pages;
