<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.mxpio</groupId>
		<artifactId>mxpio-boot-parent</artifactId>
		<relativePath>../../pom.xml</relativePath>
		<version>4.0.0-beta.2</version>
	</parent>
	<artifactId>mxpio-autoconfigure</artifactId>
	<name>自动装配模块</name>
	<description>自动装配模块</description>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven-jar-plugin.version>3.1.1</maven-jar-plugin.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-common</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-jpa</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-security</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-cache</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-system</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-cache-redis</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-cache-caffeine</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-quartz</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-camunda</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-filestorage</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-excel</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-log</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-expression</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-multitenant</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-dbconsole</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-message</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-websocket</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-datav</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-dingtalk</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-email</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-oauth</artifactId>
			<optional>true</optional>
		</dependency>
        <dependency>
            <groupId>com.mxpio</groupId>
            <artifactId>mxpio-oauth2-server</artifactId>
            <optional>true</optional>
        </dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-msal</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-wechat</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.mxpio</groupId>
			<artifactId>mxpio-lowcode</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>
</project>
