spring:
  profiles:
    active: dev
springdoc: 
  swagger-ui: 
    path: /swagger-ui.html
    url: /v3/api-docs
    enabled: true
    configs:
      - validatorUrl: ""
#  api-docs: 
#    path: /v3/api-docs
#    enabled: true