server:
  port: 9005
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path:
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: false
    showSql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://113.142.80.172:13310/mboot?characterEncoding=utf-8&useSSL=true&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 113.142.80.172
    port: 7339
    password: sideR@123#NCC_1701
    timeout: 8000
    lettuce:
      pool:
        maxActive: 8
        maxWait: -1
        maxIdle: 8
        minIdle: 0
    database: 10
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  sql:
    init:
      continue-on-error: true
      mode: always
      encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
camunda:
  bpm:
    database:
      type: mysql
      schema-update: true
    history-level: FULL
    auto-deployment-enabled: false # 自动部署 resources 下的 bpmn文件
